In [76]:
from scipy.optimize import linprog
import numpy as np
import pandas as pd
from timeit import default_timer as timer

In [77]:
cost = np.array([2, 10, 5, 8, 7, 4, 2, 2, 2, 6, 2, 1, 7, 10, 4, 7, 1, 5, 10, 4, 1, 1, 1, 3, 2, 2, 3, 7, 3, 5, 3, 3, 0])
time = np.array([1, 4, 3, 6, 6, 2, 1, 3, 2, 5, 3, 2, 2, 5, 6, 4, 5, 4, 3, 2, 4, 3, 2, 1, 2, 2, 2, 1, 3, 5, 6, 4, 3])
profit = np.array([0, 3, 1, 3, 3, 0, 0, 0, 0, 2, 1, 0, 2, 3, 2, 2, 1, 2, 2, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 2, 2, 1, 1])
area = np.array([2, 5, 8, 6, 4, 6, 6, 7, 5, 4, 5, 6, 6, 6, 4, 6, 6, 5, 5, 4, 7, 3, 5, 3, 4, 3, 4, 5, 4, 5, 6, 5, 6])
button_income_placements = np.array([4, 10, 16, 22, 28, 34, 40, 46, 52])

In [78]:
def assign(matrix, start, end, vector):
    matrix[start - 1:end] = vector

def index(matrix, start, end):
    return matrix[start - 1:end]

In [79]:
def generateArea1():
    a = np.zeros(678, dtype=np.int64)
    assign(a, 265, 297, area)
    return ([a], [81])

def generateArea2():
    a = np.zeros(678, dtype=np.int64)
    assign(a, 265, 297, area)
    assign(a, 645, 645, -1000)
    return ([a], [75])

def generateArea3():
    a = np.zeros(678, dtype=np.int64)
    assign(a, 265, 297, -area)
    assign(a, 645, 645, 76)
    return ([a], [0])

def generateTime1():
    a = np.zeros(678, dtype=np.int64)
    assign(a, 265, 297, time)
    assign(a, 595, 627, -time)
    assign(a, 628, 636, 1)
    return ([a], [52])

def generateTime2():
    a = np.zeros(678, dtype=np.int64)
    assign(a, 595, 627, 1)
    return ([a], [1])

def generateTime3():
    list = []
    for i in range(33):
        a = np.zeros(678, dtype=np.int64)
        
        assign(a, 232 + i, 232 + i, 1)
        assign(a, 265 + i, 265 + i, -1)
        assign(a, 595 + i, 595 + i, 1)

        list.append(a)
    return (list, [0 for _ in range(33)])

def generateButtonIncome1():
    list = []
    for i in range(9):
        a = np.zeros(678, dtype=np.int64)

        assign(a, 1 + i * 33, 33 + i*33, time)
        assign(a, 298 + i * 33, 330 + i * 33, -time)
        assign(a, 628 + i, 628 + i, 1)

        if i > 0:
            assign(a, 1 + (i-1) * 33, 33 + (i-1) * 33, -time)
            assign(a, 637 + i - 1, 637 + i - 1, 1)
        
        list.append(a)
    return (list, button_income_placements)

def generateButtonIncome2():
    a = np.zeros(678, dtype=np.int64)

    assign(a, 1, 33, time)
    assign(a, 628, 628, 1)
    assign(a, 637, 637, -1)
      
    return ([a], [0])

def generateButtonIncome3():
    list = []
    for i in range(8):
        a = np.zeros(678, dtype=np.int64)

        assign(a, 637 + i, 637 + i, -1)
        
        list.append(a)
    return (list, [-button_income_placements[i] for i in range(8)])

def generateButtonIncome4():
    list = []
    for i in range(7):
        a = np.zeros(678, dtype=np.int64)

        assign(a, 1 + i * 33, 33 + i * 33, -time)
        assign(a, 34 + i * 33, 66 + i * 33, time)
        assign(a, 629 + i, 629+ i, 1)
        
        assign(a, 637 + i, 637 + i, 1)
        assign(a, 638 + i, 638 + i, -1)
            
        list.append(a)
    return (list, [0 for _ in range(7)])

def generateButtonIncome5():
    list = []
    for i in range(9):
        a = np.zeros(678, dtype=np.int64)

        assign(a, 298 + i * 33, 330 + i * 33, 1)        
        list.append(a)
    return (list, [1 for _ in range(9)])

def generateButtonIncome6():
    list = []
    for i in range(9 * 33):
        a = np.zeros(678, dtype=np.int64)
    
        assign(a, 1 + i, 1 + i, -1)

        if 1 + i - 33 > 0:
            assign(a, 1 + i - 33, 1 + i - 33, 1)
        
        assign(a, 298 + i, 298 + i, 1)
            
        list.append(a)

    return (list, [0 for _ in range(9 * 33)])

def generateButtonStorage():
    list = []
    for i in range(9):
        a = np.zeros(678, dtype=np.int64)

        assign(a, 1 + i * 33, 33 + i * 33, cost)
        for j in range(i):
            assign(a, 1 + j * 33, 33 + j * 33, -profit)
            assign(a, 628, 628 + j, -1)

        list.append(a)
    return (list, [5 for _ in range(9)])

def generateCombination1():
    list = []
    for i in range(8 * 33):
        a = np.zeros(678, dtype=np.int64)

        assign(a, 1 + i, 1 + i, 1)
        assign(a, 34 + i, 34 + i, -1)
        
        list.append(a)
    return (list, [0 for _ in range(8 * 33)])

def generateCombination2():
    list = []
    for i in range(9):
        a = np.zeros(678, dtype=np.int64)

        assign(a, 1 + i * 33, 33 + i * 33, -time)
        assign(a, 628 + i, 628 + i, -1)
        
        list.append(a)
    return (list, -button_income_placements)

def generateOmageMultiplication1():
    list = []
    for i in range(33):
        a = np.zeros(678, dtype=np.int64)

        assign(a, 265 + i, 265 + i, -1)
        assign(a, 646 + i, 646 + i, 1)
        
        list.append(a)
    return (list, [0 for _ in range(33)])

def generateOmageMultiplication2():
    a = np.zeros(678, dtype=np.int64)

    assign(a, 645, 645, -33)
    assign(a, 646, 678, 1)
    
    return ([a], [0])

def generateOmageMultiplication3():
    list = []
    for i in range(33):
        a = np.zeros(678, dtype=np.int64)

        assign(a, 265 + i, 265 + i, 1)
        assign(a, 645, 645, 1)
        assign(a, 646 + i, 646 + i, -1)
        
        list.append(a)
    return (list, [1 for _ in range(33)])

def generateTemplate():
    a = np.zeros(678, dtype=np.int64)
    # assign here
    return ([a], [])

def generateTemplate2():
    list = []
    for i in range(NUMBER):
        a = np.zeros(661, dtype=np.int64)
        # assign here
        list.append(a)
    return (list, [])

In [80]:
A = []
b = []
(a_entries, b_entries) = generateArea1()
A.extend(a_entries)
b.extend(b_entries)
(a_entries, b_entries) = generateArea2()
A.extend(a_entries)
b.extend(b_entries)
(a_entries, b_entries) = generateArea3()
A.extend(a_entries)
b.extend(b_entries)

(a_entries, b_entries) = generateTime1()
A.extend(a_entries)
b.extend(b_entries)
(a_entries, b_entries) = generateTime2()
A.extend(a_entries)
b.extend(b_entries)
(a_entries, b_entries) = generateTime3()
A.extend(a_entries)
b.extend(b_entries)

(a_entries, b_entries) = generateButtonIncome1()
A.extend(a_entries)
b.extend(b_entries)
(a_entries, b_entries) = generateButtonIncome2()
A.extend(a_entries)
b.extend(b_entries)
(a_entries, b_entries) = generateButtonIncome3()
A.extend(a_entries)
b.extend(b_entries)
(a_entries, b_entries) = generateButtonIncome4()
A.extend(a_entries)
b.extend(b_entries)
(a_entries, b_entries) = generateButtonIncome5()
A.extend(a_entries)
b.extend(b_entries)
(a_entries, b_entries) = generateButtonIncome6()
A.extend(a_entries)
b.extend(b_entries)

(a_entries, b_entries) = generateButtonStorage()
A.extend(a_entries)
b.extend(b_entries)

(a_entries, b_entries) = generateCombination1()
A.extend(a_entries)
b.extend(b_entries)
(a_entries, b_entries) = generateCombination2()
A.extend(a_entries)
b.extend(b_entries)

(a_entries, b_entries) = generateOmageMultiplication1()
A.extend(a_entries)
b.extend(b_entries)
(a_entries, b_entries) = generateOmageMultiplication2()
A.extend(a_entries)
b.extend(b_entries)
(a_entries, b_entries) = generateOmageMultiplication3()
A.extend(a_entries)
b.extend(b_entries)

A = np.array(A, dtype=np.int64)
print(f'{A.shape = }')
print(A)
b = np.array(b, dtype=np.int64)
print(f'{b.shape = }')
print(b)

A.shape = (718, 678)
[[ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 ...
 [ 0  0  0 ... -1  0  0]
 [ 0  0  0 ...  0 -1  0]
 [ 0  0  0 ...  0  0 -1]]
b.shape = (718,)
[ 81  75   0  52   1   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   4  10  16  22  28  34  40  46  52   0  -4 -10 -16 -22 -28 -34
 -40 -46   0   0   0   0   0   0   0   1   1   1   1   1   1   1   1   1
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   

In [81]:
def generateObjective1():
    c = np.zeros(678, dtype=np.int64)

    assign(c, 1, 297, -np.tile(profit, 9))
    
    return c

def generateObjective2():
    c = np.zeros(678, dtype=np.int64)

    assign(c, 645, 645, -162)
    
    return c

def generateObjective3():
    c = np.zeros(678, dtype=np.int64)

    assign(c, 265, 297, -2 * area)
    
    return c

def generateObjective4():
    c = np.zeros(678, dtype=np.int64)

    assign(c, 646, 678, 2 * area)
    
    return c

def generateObjective5():
    c = np.zeros(678, dtype=np.int64)

    assign(c, 265, 297, cost)
    
    return c

def generateObjective6():
    c = np.zeros(678, dtype=np.int64)

    assign(c, 628, 636, -1)
    
    return c

In [82]:
c = [
    generateObjective1(),
    generateObjective2(),
    generateObjective3(),
    generateObjective4(),
    generateObjective5(),
    generateObjective6(),
]

c = np.array(c, dtype=np.int64)

print(c.shape)
print(c)

c = c.sum(axis=0)
print(c.shape)
print(c)

(6, 678)
[[ 0 -3 -1 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ... 12 10 12]
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]]
(678,)
[   0   -3   -1   -3   -3    0    0    0    0   -2   -1    0   -2   -3
   -2   -2   -1   -2   -2   -1   -1    0    0    0    0    0   -1   -1
   -1   -2   -2   -1   -1    0   -3   -1   -3   -3    0    0    0    0
   -2   -1    0   -2   -3   -2   -2   -1   -2   -2   -1   -1    0    0
    0    0    0   -1   -1   -1   -2   -2   -1   -1    0   -3   -1   -3
   -3    0    0    0    0   -2   -1    0   -2   -3   -2   -2   -1   -2
   -2   -1   -1    0    0    0    0    0   -1   -1   -1   -2   -2   -1
   -1    0   -3   -1   -3   -3    0    0    0    0   -2   -1    0   -2
   -3   -2   -2   -1   -2   -2   -1   -1    0    0    0    0    0   -1
   -1   -1   -2   -2   -1   -1    0   -3   -1   -3   -3    0    0    0
    0   -2   -1    0   -2   -3   -2   -2   -1   -2   -2   -1   -1    0
    0    0    0    0   -1   -1   -1   -2   -2   -1  

In [94]:
X_bounds = []
X_bounds.extend([(0,1) for _ in range(33 * 9 * 2 + 33)]) # X, Y, z
X_bounds.extend([(0,100) for _ in range(9)]) # ψ
X_bounds.extend([(0,500) for _ in range(8)]) # ξ
X_bounds.extend([(0,1)]) # λ
X_bounds.extend([(0,1) for _ in range(33)]) # ω
    
print(f'{c.shape = }')
print(f'{A.shape = }')
print(f'{b.shape = }')

start = timer()
res = linprog(c, A_ub=A, b_ub=b, bounds=X_bounds, integrality=1, options={
    'presolve': False, # disable as it can cause errors
    'disp': True,
    'primal_feasibility_tolerance': 1e-10, # use the minimum tolerance possible for both primal and dual
    'dual_feasibility_tolerance': 1e-10
}, method='highs')
end = timer()
print(res)
print(f'Solver took {end - start}s')

c.shape = (678,)
A.shape = (718, 678)
b.shape = (718,)
        message: Optimization terminated successfully. (HiGHS Status 7: Optimal)
        success: True
         status: 0
            fun: -234.0
              x: [ 0.000e+00  0.000e+00 ... -0.000e+00  1.000e+00]
            nit: -1
          lower:  residual: [ 0.000e+00  0.000e+00 ... -0.000e+00
                              1.000e+00]
                 marginals: [ 0.000e+00  0.000e+00 ...  0.000e+00
                              0.000e+00]
          upper:  residual: [ 1.000e+00  1.000e+00 ...  1.000e+00
                              0.000e+00]
                 marginals: [ 0.000e+00  0.000e+00 ...  0.000e+00
                              0.000e+00]
          eqlin:  residual: []
                 marginals: []
        ineqlin:  residual: [ 5.000e+00  9.990e+02 ...  0.000e+00
                              0.000e+00]
                 marginals: [ 0.000e+00  0.000e+00 ...  0.000e+00
                              0.000e+00]
 mip_nod

In [111]:
res.x = res.x.astype(np.int64)

print(f"Value = {int(-1 * res.fun)}")
print(f"   Profit = {-1 * (-1 * res.x[1-1:297] * np.tile(profit, 9)).sum()} (Old)")
print(f"   Area = {-1 * (-2 * res.x[265-1:297] * area).sum()} (Covered {(res.x[265-1:297] * area).sum()})")
print(f"   Cost = {-1 * (res.x[265-1:297] * cost).sum()}")
print(f"patches             = {np.argwhere(index(res.x, 265, 297)).squeeze()}")
area_cost = index(res.x, 265, 297) * area;
print(f"patches area        = {area_cost[area_cost > 0]} (sum = {area_cost[area_cost > 0].sum()})")
time_cost = index(res.x, 265, 297) * time;
print(f"patches time cost   = {time_cost[time_cost > 0]} (sum = {time_cost[time_cost > 0].sum()})")
button_cost = index(res.x, 265, 297) * cost;
print(f"patches button cost = {button_cost[button_cost > 0]} (sum = {button_cost[button_cost > 0].sum()})")

print(f"patches [1]         = {np.argwhere(index(res.x, 1, 33)).squeeze()}")
print(f"patches [2]         = {np.argwhere(index(res.x, 34, 66)).squeeze()}")
print(f"patches [3]         = {np.argwhere(index(res.x, 67, 99)).squeeze()}")
print(f"patches [4]         = {np.argwhere(index(res.x, 100, 132)).squeeze()}")
print(f"patches [5]         = {np.argwhere(index(res.x, 133, 165)).squeeze()}")
print(f"patches [6]         = {np.argwhere(index(res.x, 166, 198)).squeeze()}")
print(f"patches [7]         = {np.argwhere(index(res.x, 199, 231)).squeeze()}")
print(f"patches [8]         = {np.argwhere(index(res.x, 232, 264)).squeeze()}")
print(f"patches [9]         = {np.argwhere(index(res.x, 265, 297)).squeeze()}")

print(f"x[9] = {np.round(index(res.x, 265, 297))}")
print(f"x =\n{np.round(index(res.x, 1, 297)).reshape(9,33)}")
print(f"y =\n{np.round(index(res.x, 298, 594)).reshape(9,33)}")
print(f"z = {np.round(index(res.x, 595, 627))}")
print(f"ψ = {np.round(index(res.x, 628, 636))}")
print(f"ξ = {np.round(index(res.x, 637, 644))}")
print(f"λ = {np.round(index(res.x, 645, 645)[0])}")
print(f"ω = {np.round(index(res.x, 646, 678))}")
print("\ngiven constants")
print(f"b = {button_income_placements}")
print(f"t = {time}")
print(f"p = {profit}")
print(f"a = {area}")
print(f"c = {cost}")

# ID FELDER KNOPF_KOSTEN ZEIT_KOSTEN KNOPF_EINKOMMEN FORMEL

Value = 234
   Profit = 104 (Old)
   Area = 142 (Covered 71)
   Cost = -43
patches             = [ 1  4  6 10 11 12 16 17 20 22 26 30 32]
patches area        = [5 4 6 5 6 6 6 5 7 5 4 6 6] (sum = 71)
patches time cost   = [4 6 1 3 2 2 5 4 4 2 2 6 3] (sum = 44)
patches button cost = [10  7  2  2  1  7  1  5  1  1  3  3] (sum = 43)
patches [1]         = [17 32]
patches [2]         = [17 30 32]
patches [3]         = [ 4 17 30 32]
patches [4]         = [ 4 17 29 30 32]
patches [5]         = [ 1  4 17 26 29 30 32]
patches [6]         = [ 1  4 10 12 17 26 30 32]
patches [7]         = [ 1  4 10 12 17 20 22 26 30 32]
patches [8]         = [ 1  4 10 11 12 17 20 22 26 30 32]
patches [9]         = [ 1  4  6 10 11 12 16 17 20 22 26 30 32]
x[9] = [0 1 0 0 1 0 1 0 0 0 1 1 1 0 0 0 1 1 0 0 1 0 1 0 0 0 1 0 0 0 1 0 1]
x =
[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1]
 [0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0

In [112]:
print((np.round(A[3-1]).astype(np.int64) * np.round(res.x.astype(np.int64))).sum())
print(np.round(A[3-1]).astype(np.int64) * np.round(res.x.astype(np.int64)))
print(np.round(A[3-1]).astype(np.int64))
print(np.round(res.x).astype(np.int64))
#A[3-1][645-1]

5
[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0 -5  0  0 -4  0 -6  0  0  0 -5 -6 -6  0  0  0 -6 -5  0  0 -7  0 -5  0
  0  0 -4  0  0  0 -6  0 -6  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 

In [85]:
def header_name(index):
    # this could be made more efficent with index multiplication and modulo but this works
    if index <= 33:
        return f'{index} - col(X)=1'
    if index <= 66:
        return f'{index} - col(X)=2'
    if index <= 99:
        return f'{index} - col(X)=3'
    if index <= 132:
        return f'{index} - col(X)=4'
    if index <= 165:
        return f'{index} - col(X)=5'
    if index <= 198:
        return f'{index} - col(X)=6'
    if index <= 231:
        return f'{index} - col(X)=7'
    if index <= 264:
        return f'{index} - col(X)=8'
    if index <= 297:
        return f'{index} - col(X)=9'
    
    if index <= 330:
        return f'{index} - col(Y)=1'
    if index <= 363:
        return f'{index} - col(Y)=2'
    if index <= 396:
        return f'{index} - col(Y)=3'
    if index <= 429:
        return f'{index} - col(Y)=4'
    if index <= 462:
        return f'{index} - col(Y)=5'
    if index <= 495:
        return f'{index} - col(Y)=6'
    if index <= 528:
        return f'{index} - col(Y)=7'
    if index <= 561:
        return f'{index} - col(Y)=8'
    if index <= 594:
        return f'{index} - col(Y)=9'
    
    if index <= 627:
        return f'{index} - z'

    if index <= 636:
        return f'{index} - ψ'

    if index <= 644:
        return f'{index} - ξ'
    
    if index == 645:
        return f'{index} - λ'

    if index <= 678:
        return f'{index} - ω'

    if index == 679:
        return 'f - Ax <= b'
    
    raise Exception(f"Invalid index {index}")

header = list(map(header_name, (i + 1 for i in range(679))))

df = pd.DataFrame(A)
df['b'] = b
df.to_excel('Inequalites.xlsx', index=False, header=header)