In [1]:
import numpy as np

In [2]:
cost = np.array([2, 10, 5, 8, 7, 4, 2, 2, 2, 6, 2, 1, 7, 10, 4, 7, 1, 5, 10, 4, 1, 1, 1, 3, 2, 2, 3, 7, 3, 5, 3, 3, 0])
time = np.array([1, 4, 3, 6, 6, 2, 1, 3, 2, 5, 3, 2, 2, 5, 6, 4, 5, 4, 3, 2, 4, 3, 2, 1, 2, 2, 2, 1, 3, 5, 6, 4, 3])
profit = np.array([0, 3, 1, 3, 3, 0, 0, 0, 0, 2, 1, 0, 2, 3, 2, 2, 1, 2, 2, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 2, 2, 1, 1])
area = np.array([2, 5, 8, 6, 4, 6, 6, 7, 5, 4, 5, 6, 6, 6, 4, 6, 6, 5, 5, 4, 7, 3, 5, 3, 4, 3, 4, 5, 4, 5, 6, 5, 6])
button_income_placements = np.array([4, 10, 16, 22, 28, 34, 40, 46, 52])

$2 \cdot Felder - \text{KnopfKosten} + \text{Knopfeinkommen} \cdot \alpha$


In [18]:
np.set_printoptions(linewidth=100000)

print(np.arange(0, 33))
print(-cost + area * 2 + profit * 1 - time)
print(-cost + area * 2 + profit * 2 - time)

value = -cost + area * 2 + profit * 1 - time
print(np.argwhere(value < 0).squeeze())
print(np.argwhere(value == 0).squeeze())


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32]
[ 1 -1  9  1 -2  6  9  9  6 -1  6  9  5  0  0  3  7  3 -1  3 10  2  7  2  4  2  4  3  3  2  5  4 10]
[ 1  2 10  4  1  6  9  9  6  1  7  9  7  3  2  5  8  5  1  4 11  2  7  2  4  2  5  4  4  4  7  5 11]
[ 1  4  9 18]
[13 14]
